name: Build wasm packages
description: |
  Build a list of R packages for WebAssembly, create an R library, and build a
  CRAN-like repository containing the R package binaries.
inputs:
  packages:
    description: A file containing a list of R package references.
    default: packages
    required: true
  upload-image:
    description: |
      Should the R package library filesystem image be uploaded as an artifact?
    default: true
    required: true
  upload-repo:
    description: |
      Should the R package repository be uploaded as an artifact?
    default: true
    required: true
  strip:
    description: |
      An R expression evaluating to a character vector of directories to strip
      when building the R package library image.
    default: "NULL"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install the pak and rwasm R packages
      shell: Rscript {0}
      run: |
        if (!require("pak", character.only = TRUE)) install.packages("pak")
        pak::pak("r-wasm/rwasm")
    - name: Build Wasm R packages
      shell: Rscript {0}
      run: |
        rwasm::add_list("${{ inputs.packages }}")
        rwasm::make_vfs_library(strip = ${{ inputs.strip }})
    - name: Upload R package repository
      if: ${{ inputs.upload-repo == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: wasm-repo
        path: repo
    - name: Upload R package library filesystem image
      if: ${{ inputs.upload-image == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: wasm-image
        path: |
          vfs/library.data
          vfs/library.js.metadata
